var app = new Vue({
    el: '#app',
    data: {
        columns:[
            {
                title:' ',
                type:'selection',
                key:'select',
                width:80
            },
            {
                title:'指标项名称',
                key:'name',
                tree: true
            },
            {
                title:'权重',
                key:'weight',
                width:120
            }
        ],
        quatoList:[]
    },
    mounted: function () {
        this.quatoList=[
            {
                id:'100',
                name:'科学研究水平',
                cellClassName:{
                    name:'bh-table-tree-level-1',
                    weight:'bh-table-tree-level-1',
                    select:'bh-table-tree-level-1'
                },
                children:[
                    {
                        id:'100000',
                        name:'科研获奖',
                        cellClassName:{
                            name:'bh-table-tree-level-2',
                            weight:'bh-table-tree-level-2',
                            select:'bh-table-tree-level-2'
                        },
                    },
                    {
                        id:'100001',
                        name:'国家级奖项',
                        cellClassName:{
                            name:'bh-table-tree-level-2',
                            weight:'bh-table-tree-level-2',
                            select:'bh-table-tree-level-2'
                        },
                    },
                    {
                        id:'100002',
                        name:'省部级奖项',
                        cellClassName:{
                            name:'bh-table-tree-level-2',
                            weight:'bh-table-tree-level-2',
                            select:'bh-table-tree-level-2'
                        },
                    }
                ]
            },
            {
                id:'101',
                name:'科学研究水平',
                cellClassName:{
                    name:'bh-table-tree-level-1',
                    weight:'bh-table-tree-level-1',
                    select:'bh-table-tree-level-1'
                },
                children:[
                    {
                        id:'101000',
                        name:'科研获奖',
                        cellClassName:{
                            name:'bh-table-tree-level-2',
                            weight:'bh-table-tree-level-2',
                            select:'bh-table-tree-level-2'
                        },
                        children:[
                            {
                                id:'10100000',
                                name:'科研获奖-1',
                                cellClassName:{
                                    name:'bh-table-tree-level-3',
                                    weight:'bh-table-tree-level-3',
                                    select:'bh-table-tree-level-3'
                                },
                            },
                            {
                                id:'10100101',
                                name:'国家级奖项-1',
                                cellClassName:{
                                    name:'bh-table-tree-level-3',
                                    weight:'bh-table-tree-level-3',
                                    select:'bh-table-tree-level-3'
                                },
                            },
                            {
                                id:'10100202',
                                name:'省部级奖项-1',
                                cellClassName:{
                                    name:'bh-table-tree-level-3',
                                    weight:'bh-table-tree-level-3',
                                    select:'bh-table-tree-level-3'
                                },
                            }
                        ]
                    },
                    {
                        id:'101001',
                        name:'国家级奖项',
                        cellClassName:{
                            name:'bh-table-tree-level-2',
                            weight:'bh-table-tree-level-2',
                            select:'bh-table-tree-level-2'
                        },
                    },
                    {
                        id:'101002',
                        name:'省部级奖项',
                        cellClassName:{
                            name:'bh-table-tree-level-2',
                            weight:'bh-table-tree-level-2',
                            select:'bh-table-tree-level-2'
                        },
                    }
                ]
            }
        ]
    },
    methods: {

    }
})